### PR TITLE
Add jacocoTestReport to the check command

### PR DESCRIPTION
**Pull request by simonepri**
The check task, which is run by Travis, needs to depend on jacocoTestReport.

### CODE REVIEW

**Comment by simonepri** [comment]
@stevepeak can you verify if this change can affect cicleci example??
Should this line be removed??
https://github.com/codecov/example-gradle/blob/master/circle.yml#L3

I mean, by adding:
`check.dependsOn jacocoTestReport`
we are saying that when `check` command is performed, `jacocoTestReport` is performed also.

So now the circleci exeple executes `jacocoTestReport` 2 times.
Am I wrong??

**Comment by simonepri** [comment]
Also the readme should be updated.
Let me know about.

**Comment by simonepri** [comment]
Otherwise another solution could be to add it to `.travis.yml` and remove the `dependsOn` from `gradle.build`

See an exemple:
https://github.com/ottlinger/fotocollector/blob/master/.travis.yml#L16-L18

Let me know which solution seems more cleaner to you.

**Comment by simonepri** [comment]
@stevepeak any news about that?

**Comment by stevepeak** [comment]
Hey, I've very open to pull requests to update our docs. I'm not personally familiar with Gradle, so it's hard for me to review and comment.

**Pull request merged**
